[tool.bumpversion]
current_version = "0.10.0"
parse = "^(?P<major>0|[1-9]\\d*)\\.(?P<minor>0|[1-9]\\d*)\\.(?P<patch>0|[1-9]\\d*)(?:-(?P<prerelease>(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+(?P<buildmetadata>[0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$"
serialize = [
    "{major}.{minor}.{patch}-{prerelease}+{buildmetadata}",
    "{major}.{minor}.{patch}-{prerelease}",
    "{major}.{minor}.{patch}+{buildmetadata}",
    "{major}.{minor}.{patch}",
]

[[tool.bumpversion.files]]
filename = "README.md"
search = "{current_version}"
replace = "{new_version}"
