language: node_js

services:
  - docker

env:
  - SERVER_AUTH_TYPE=basic SERVER_URL=http://127.0.0.1:5984 SERVER_USERNAME=admin SERVER_PASSWORD=password WIREMOCK_URL=http://127.0.0.1:8080 WIREMOCK_PORT=8080

before_install:
  - bash scripts/setup_couch.sh
  - bash scripts/setup_wiremock.sh

install: npm ci --no-audit

sudo: false

node_js:
- 14
- 16
- 17

script:
- npm run build
- npm run test-travis || travis_terminate 1
- npm run lint

after_success:

# - scripts/jsdoc/publish.sh - currently in progress

# To enable semantic-release, uncomment this section.
# deploy:
# - provider: script
#   skip_cleanup: true
#   script: npx semantic-release
#   on:
#     node: 12
#     branch: master
